
server:
  port: 8888
spring:
  application:
    name: confsvr
#  profiles:
#   active: native
  cloud:
    config:
      server:
        git:
          uri: https://github.com/liuyanglxh/spring-cloud-config/
          searchPaths: ucenter, business

#        native:
#          search-locations: file:///Users/liuyang/Documents/personal/configsvr/src/main/resources/config/ucenter,/Users/liuyang/Documents/personal/configsvr/src/main/resources/config/business
#